#include <jni.h>
#include "com_example_VehicleDiagnostics.h"  // generated by `javac -h`

JNIEXPORT void JNICALL Java_com_example_VehicleDiagnostics_getSensorValues
  (JNIEnv *env, jobject thiz, jobject sensorObj, jint param) {

 // lets ignore the param input and lets assume we called some function which takes the param as input

if (!sensorObj) return;

jclass sensorCls = (*env)->GetObjectClass(env, sensorObj);
if (!sensorCls) return;

jfieldID fidIdsensor1     = (*env)->GetFieldID(env, sensorCls, "sensor1", "I");
jfieldID fidIdsensor2     = (*env)->GetFieldID(env, sensorCls, "sensor2", "D");

if (!fidIdsensor1 || !fidIdsensor2 ) {
    if ((*env)->ExceptionCheck(env)) return; // propagate NoSuchFieldError if thrown
    jclass nse = (*env)->FindClass(env, "java/lang/NoSuchFieldError");
    if (nse) (*env)->ThrowNew(env, nse, "Missing EngineECU field(s)");
    return;
}

// Initialize values (demo)
(*env)->SetIntField(env, sensorObj, fidIdsensor1, 101);
(*env)->SetDoubleField(env, sensorObj, fidIdsensor2, 2.47);
}


